spring.application.name=organizer

spring.datasource.url=jdbc:mysql://localhost:3306/pickup_games
spring.datasource.username=root
spring.datasource.password=avispa07
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

